# Homebrew Brewfile
# Generated automatically for dotfiles restoration

# Taps
tap "caarlos0/tap"
tap "homebrew/services"
tap "mongodb/brew"

# Brews
brew "caarlos0/tap/timer"
brew "clang-build-analyzer"
brew "exiftool"
brew "fd"
brew "ffmpegthumbnailer"
brew "fzf"
brew "gcc"
brew "gh"
brew "git"
brew "git-delta"
brew "go"
brew "imagemagick"
brew "just"
brew "lazygit"
brew "libmagic"
brew "luarocks"
brew "mariadb", restart_service: :changed
brew "maven"
brew "mingw-w64"
brew "mole"
brew "mongodb/brew/mongodb-community"
brew "neovim"
brew "node"
brew "nvm"
brew "pipx"
brew "pkgconf"
brew "postgresql@16", restart_service: :changed
brew "powerlevel10k"
brew "python@3.14"
brew "redis", restart_service: :changed
brew "ripgrep"
brew "starship"
brew "stow"
brew "terminal-notifier"
brew "tmux"
brew "tree-sitter"
brew "uv"
brew "yazi"
brew "z"
brew "zoxide"

# Casks
cask "anaconda"
cask "claude-code"
cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
cask "kitty"
cask "ngrok"

# VS Code Extensions
vscode "biomejs.biome"
vscode "bradlc.vscode-tailwindcss"
vscode "burkeholland.simple-react-snippets"
vscode "digitalbrainstem.javascript-ejs-support"
vscode "dsznajder.es7-react-js-snippets"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "expo.vscode-expo-tools"
vscode "formulahendry.auto-rename-tag"
vscode "formulahendry.code-runner"
vscode "golang.go"
vscode "gxl.git-graph-3"
vscode "humedessie.mongo-playground"
vscode "ms-azuretools.vscode-containers"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpp-devtools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.live-server"
vscode "msjsdiag.vscode-react-native"
vscode "oxc.oxc-vscode"
vscode "pkief.material-icon-theme"
vscode "prisma.prisma"
vscode "redhat.java"
vscode "redhat.vscode-yaml"
vscode "ritwickdey.liveserver"
vscode "tomoki1207.pdf"
vscode "twxs.cmake"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vue.volar"
vscode "zhuangtongfa.material-theme"
