add_newline = false

[character]
success_symbol = "[➜](green)"
error_symbol = "[✗](red)"

[directory]
truncation_length = 3
home_symbol = ""

[git_branch]
symbol = " "
style = "#ff79c6"

[git_status]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true
