return {
  '3rd/image.nvim',
  lazy = true,
  ft = { 'markdown', 'vimwiki', 'asciidoc', 'typst', 'neorg' },
  config = function()
    require('image').setup {
      backend = 'kitty',
      processor = 'magick_cli',
      integrations = {
        markdown = {
          enabled = true,
          clear_in_insert_mode = false,
          download_remote_images = true,
          only_render_image_at_cursor = false,
          floating_windows = false,
          filetypes = { 'markdown', 'vimwiki' },
        },
        asciidoc = { enabled = true },
        typst = { enabled = true },
        neorg = { enabled = true },
        syslang = { enabled = true },
        html = { enabled = false },
        css = { enabled = false },
        org = { enabled = false },
      },
      max_width_window_percentage = 100,
      max_height_window_percentage = 80,
      kitty_method = 'normal',
      window_overlap_clear_enabled = true,
      window_overlap_clear_ft_ignore = {
        'cmp_menu',
        'cmp_docs',
        'snacks_notif',
        'scrollview',
        'scrollview_sign',
        'TelescopePrompt',
        'TelescopeResults',
      },
      editor_only_render_when_focused = true,
      tmux_show_only_in_active_window = true,
      hijack_file_patterns = {
        '*.png',
        '*.jpg',
        '*.jpeg',
        '*.gif',
        '*.webp',
        '*.avif',
        '*.bmp',
        '*.ico',
        '*.heic',
        '*.heif',
        '*.svg',
      },
    }
  end,
}
